# Generated by Django 5.2.12 on 2026-06-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_fix_ollama_model_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandlog",
            name="agent",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="generatedfile",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="generatedfile",
            name="iteration",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
