# Generated by Django 5.2.12 on 2026-06-08 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_simplify_prompt_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="benchmarkrun",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="completion_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="cpu_temp_c_peak",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="disk_free_gb",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="gpu_percent_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="gpu_percent_peak",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="gpu_temp_c_peak",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="prompt_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="tokens_per_second",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="vram_total_mb",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="vram_used_mb_peak",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ResourceSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elapsed_seconds", models.FloatField(default=0.0)),
                ("cpu_percent", models.FloatField(blank=True, null=True)),
                ("ram_used_mb", models.FloatField(blank=True, null=True)),
                ("ram_total_mb", models.FloatField(blank=True, null=True)),
                ("gpu_percent", models.FloatField(blank=True, null=True)),
                ("vram_used_mb", models.FloatField(blank=True, null=True)),
                ("vram_total_mb", models.FloatField(blank=True, null=True)),
                ("gpu_temp_c", models.FloatField(blank=True, null=True)),
                ("cpu_temp_c", models.FloatField(blank=True, null=True)),
                ("disk_free_gb", models.FloatField(blank=True, null=True)),
                ("tokens_per_second", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_samples",
                        to="dashboard.modelrun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
