# Generated by Django 5.2.12 on 2026-06-08 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_autonomous_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Laukia"),
                            ("running", "Vykdoma"),
                            ("succeeded", "Baigta"),
                            ("failed", "Nepavyko"),
                            ("cancelled", "Atšaukta"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=190, unique=True)),
                ("sandbox_path", models.CharField(blank=True, max_length=600)),
                (
                    "origin",
                    models.CharField(
                        choices=[("new", "Naujas"), ("existing", "Esamas")],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="modelrun",
            name="user_prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="modelrun",
            name="benchmark",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_runs",
                to="dashboard.benchmarkrun",
            ),
        ),
        migrations.AlterField(
            model_name="previewserver",
            name="model_run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preview",
                to="dashboard.modelrun",
            ),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turns",
                to="dashboard.chat",
            ),
        ),
        migrations.CreateModel(
            name="PendingInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("question", "Klausimas"),
                            ("approval", "Patvirtinimas"),
                        ],
                        default="question",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("options", models.JSONField(blank=True, default=list)),
                ("command", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Laukia"),
                            ("answered", "Atsakyta"),
                            ("denied", "Atmesta"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "model_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="dashboard.modelrun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="dashboard.project",
            ),
        ),
        migrations.AddField(
            model_name="previewserver",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preview",
                to="dashboard.project",
            ),
        ),
    ]
