# Generated by Django 5.2.12 on 2026-06-09 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_project_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="benchmarkrun",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="benchmarks",
                to="dashboard.project",
            ),
        ),
    ]
