# Generated by Django 5.2.12 on 2026-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_remove_modelrun_benchmark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_loose",
            field=models.BooleanField(default=False),
        ),
    ]
